FROM node:12.13.1 as stage1
WORKDIR /usr/src/app
COPY package.json ./
RUN npm install

FROM node:12.13.1-buster-slim
WORKDIR /usr/src/app
COPY . /usr/src/app
COPY --from=stage1 /usr/src/app /usr/src/app
RUN npm install pm2 -g
ENV PM2_PUBLIC_KEY 7aszkmdsc4enc3o
ENV PM2_SECRET_KEY iyph326860n5d9m
EXPOSE 3000
RUN ls -al
CMD ["pm2-runtime","server.js","--name","apiserver"]
